-- Prahari · Supabase schema (run in the Supabase SQL editor)
-- Runtime model: scan rows + full analysis JSON. The result JSON is the
-- API's single source of truth (sessions/findings/certs are derived views
-- generated by the pipeline). Reports are built on the fly — there is no
-- reports table.
--
-- Access model: the tool is open (no user accounts). The backend is the
-- only DB client and uses the service-role key, which bypasses RLS.
-- RLS below is enabled with NO policies on purpose: the anon key can
-- read nothing even if it leaks.
--
-- NOTE: there are deliberately NO GENERATED columns in this schema —
-- `is_expired` / `days_to_expiry` are computed by the pipeline at insert
-- time (a `now()`-dependent expression is not IMMUTABLE and Postgres
-- rejects it inside GENERATED ALWAYS ... STORED).

-- ============ scans ============
create table if not exists public.scans (
  id            uuid primary key,
  name          text not null,
  file_size     bigint not null,
  file_path     text not null,
  status        text not null default 'uploaded'
                check (status in ('uploaded','parsing','complete','failed')),
  progress      smallint not null default 0,
  error         text,
  posture_score smallint check (posture_score between 0 and 100),
  grade         char(1) check (grade in ('A','B','C','D','F')),
  protocol_counts jsonb not null default '{}',
  session_count int,
  started_at    timestamptz,
  completed_at  timestamptz,
  created_at    timestamptz not null default now()
);
create index if not exists scans_created on public.scans (created_at desc);

-- ============ scan_results (full pipeline JSON, one per scan) ============
create table if not exists public.scan_results (
  scan_id    uuid primary key references public.scans(id) on delete cascade,
  data       jsonb not null,
  updated_at timestamptz not null default now()
);

-- ============ RLS ============
-- Enabled with no policies: the anon key is locked out entirely; only the
-- service-role key (the backend) can touch these tables.
alter table public.scans enable row level security;
alter table public.scan_results enable row level security;

-- ============ storage ============
-- Bucket (create once in the dashboard): 'pcaps' — PRIVATE.
-- Path convention: <scan_id>.pcap under 'pcaps'.
-- Retention: the backend deletes pcap objects ~24h after scan completion
-- (opportunistic cleanup on list requests — see app/db/client.py).
-- Storage objects are accessed with the service role key from Render; the
-- anon key never reads them.
