-- Prahari — SecureMailScope · Supabase schema (run in the Supabase SQL editor)
-- Runtime model: scan rows + full analysis JSON + report rows. The result
-- JSON is the API's single source of truth (sessions/findings/certs are
-- derived views generated by the pipeline).
--
-- NOTE: there are deliberately NO GENERATED columns in this schema —
-- `is_expired` / `days_to_expiry` are computed by the pipeline at insert
-- time (a `now()`-dependent expression is not IMMUTABLE and Postgres
-- rejects it inside GENERATED ALWAYS ... STORED).

-- ============ scans ============
create table if not exists public.scans (
  id            uuid primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  name          text not null,
  file_size     bigint not null,
  file_path     text not null,
  status        text not null default 'uploaded'
                check (status in ('uploaded','parsing','complete','failed')),
  progress      smallint not null default 0,
  error         text,
  posture_score smallint check (posture_score between 0 and 100),
  grade         char(1) check (grade in ('A','B','C','D','F')),
  protocol_counts jsonb not null default '{}',
  session_count int,
  started_at    timestamptz,
  completed_at  timestamptz,
  created_at    timestamptz not null default now()
);
create index if not exists scans_user_created on public.scans (user_id, created_at desc);

-- ============ scan_results (full pipeline JSON, one per scan) ============
create table if not exists public.scan_results (
  scan_id    uuid primary key references public.scans(id) on delete cascade,
  data       jsonb not null,
  updated_at timestamptz not null default now()
);

-- ============ reports ============
create table if not exists public.reports (
  id           uuid primary key default gen_random_uuid(),
  scan_id      uuid not null references public.scans(id) on delete cascade,
  format       text not null check (format in ('json','html','pdf')),
  file_path    text not null,
  generated_at timestamptz not null default now()
);

-- ============ RLS ============
alter table public.scans enable row level security;
alter table public.scan_results enable row level security;
alter table public.reports enable row level security;

drop policy if exists "own scans" on public.scans;
create policy "own scans" on public.scans
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own results" on public.scan_results;
create policy "own results" on public.scan_results
  for all using (exists (
    select 1 from public.scans s
    where s.id = scan_id and s.user_id = auth.uid()));

drop policy if exists "own reports" on public.reports;
create policy "own reports" on public.reports
  for all using (exists (
    select 1 from public.scans s
    where s.id = scan_id and s.user_id = auth.uid()));

-- ============ storage ============
-- Buckets (create in dashboard or via API): 'pcaps', 'reports' — both PRIVATE.
-- Path convention: <user_id>/<scan_id>.pcap under 'pcaps'.
-- Retention: the backend deletes pcap objects ~24h after scan completion
-- (opportunistic cleanup on list requests — see app/db/client.py).
-- Storage objects are accessed with the service role key from Render; the
-- anon key never reads them, and RLS on the tables is the user boundary.
